version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/cs3238-tsuzu/sqlx-selector
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -v ./...